### ISSUE TITLE
Hello Dario, may we talk ? 

### ISSUE THREAD

**Issue by KoreTeknology** [KoreTeknology/Blender-Generative-AI-Addon#2]
Hi Dario @kant ...i gave seen various text corrections from you on my documentations projects... nothing bad here :) but i am wondering who you are.
i am used to know people who contributes, and i am curious to know you... can we chat ?
Thank you very much, have a nice day
uriel

**Comment by kant** [comment]
I'm buddhist, so [mushotoku](https://www.zen-buddhism.net/zen-concepts/mushotoku.html) is my humble answer. Simply as that. For sure, we can talk.

**Comment by KoreTeknology** [comment]
i was thinking you are a bot ! :) i did practice Zen also, in front of the wall :) have a nice day, bye

**Comment by kant** [comment]
Not, I am not a bot. Please, check my [GoodReads account](https://www.goodreads.com/user/show/1026538-dar-o-here). Anyway, you are free to think anything. Best karma for you and your family!

**Comment by KoreTeknology** [comment]
Thank you for your answer, good to know! of course we are free to think, thats why we are on github ;) bye, take care
